ARG ELK_VERSION

# https://www.docker.elastic.co/
#FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}
FROM docker.elastic.co/kibana/kibana:7.3.1
# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
